name: Laravel auto-deploy

on:
  push:
    branches: [ dev]
  pull_request:
    branches: [ master]

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run:  composer install --no-interaction --prefer-dist --optimize-autoloader
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/furkanaymergen.site
            git pull
            php artisan migrate --force
            php artisan optimize:clear


