name: Laravel auto-deploy

on:
  push:
    branches: [ dev]
  pull_request:
    branches: [ master]

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run:  composer install --no-interaction --prefer-dist --optimize-autoloader
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Clear Caches
      run: php artisan optimize:clear


