name: Laravel auto-deploy

on:
  push:
    branches: [ dev]
  pull_request:
    branches: [ master]

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run:  composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Clear Caches
      run: php artisan optimize:clear

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
        REMOTE_PASSWORD: ${{ secrets.REMOTE_USERNAME }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        TARGET: "/var/www/furkanaymergen.site"
